spring: 
 profiles: 
  active: 
   - dev
   
---  
server: 
 port: 8201
spring: 
 profiles: dev
 application: 
  name: mscloud-config-client
eureka: 
 client: 
  service-url: 
   defaultZone: http://192.168.0.124:7001/eureka/
  
---
server: 
 port: 8202
spring: 
 profiles: test
 application: 
  name: mscloud-config-client
eureka: 
 client: 
  service-url: 
   defaultZone: http://192.168.0.124:7001/eureka/
  
